version: '3'

services:

  django:
    build: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:
    driver: local

networks:
  backend:
    driver: bridge